### ISSUE TITLE
remove font-family

### ISSUE THREAD

**Issue by zaggino** [yasinkuyu/brackets-atom-dark#2]
You can define font-family in the `Theme Settings` dialog, it shouldn't be hard-coded in the theme: https://github.com/yasinkuyu/brackets-atom-dark/blob/master/main.less#L12-L15
![image](https://cloud.githubusercontent.com/assets/1067319/7508607/745c72c0-f4c6-11e4-80b1-107f2a8258a2.png)

**Comment by yasinkuyu** [comment]
Thanks for the suggestion.
